# This file makes Travis continous integration (CI) run
#
# Documentation: http://docs.travis-ci.com/user/languages/julia/
#
# https://github.com/invenia/Mocking.jl/blob/master/.travis.yml
language: julia
os:
  - linux
julia:
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
# https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999
