name = "Viruses"
uuid = "454e98af-4eba-4cba-91ee-70bd83476937"
authors = ["Mauro Werder <mauro3@runbox.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
